### PR TITLE
Propose a scratch for newsletter.

### PR DESCRIPTION
**Pull request by jhchabran**
It's a lot of work to write the newsletter all at once. So what about
instead doing it as we go or notice others taking DX initiatives?

### CODE REVIEW

**Comment by burmudar** [comment]
I was thinking about this over the weekend. Is there a label we can attach which will allow us to curate stuff that should be included into the newsletter easier ?

**Review by burmudar — APPROVED** [review]

**Comment by jhchabran** [comment]
We have the `dx-announce` label for that purpose. But sometimes, it's a bit hard to remember the exact context.

**Comment by burmudar** [comment]
Ah right gotcha 👍🏼

**Comment by bobheadxi** [comment]
I wonder if instead we should just start a long-lived branch in the handbook repo immediately after each newsletter?

**Review by bobheadxi — CHANGES_REQUESTED** [review]
For the current newsletter: https://github.com/sourcegraph/handbook/pull/3884

IMO we should just start a branch in the handbook repo and continuously update a draft there - I think it's less friction and less duplicated writing

**Pull request closed without merging**
